package basesDeDatos;

import java.sql.*;

/**
 *
 * @author JazBass
 */
public class formmodificar extends javax.swing.JFrame {

    public controlbd miagenda;

    public formmodificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtPoblacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtProvincia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnModifica = new javax.swing.JButton();
        btbCerrar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre y Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel5.setText("Población");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel6.setText("Télefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel7.setText("Correo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel8.setText("Edad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel9.setText("Provincia");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        txtNombre.setEditable(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        txtApellido.setEditable(false);
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 210, -1));

        txtDNI.setEditable(false);
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        txtDireccion.setEditable(false);
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 330, -1));

        txtPoblacion.setEditable(false);
        getContentPane().add(txtPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, -1));

        txtTelefono.setEditable(false);
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 150, -1));

        txtCorreo.setEditable(false);
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 150, -1));

        txtEdad.setEditable(false);
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        txtProvincia.setEditable(false);
        getContentPane().add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 10));

        btnModifica.setText("Mostrar Datos");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btbCerrar.setText("Cerrar");
        btbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 90, 110, -1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        jLabel10.setText("DNI:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        btnAplicar.setText("Aplicar cambios");
        btnAplicar.setEnabled(false);
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        try {
            ResultSet r;//Para almacenar la consulta
            //Pedimos el dni(Primary Key) 
            r = miagenda.consulta("dni", txtValor.getText());
            if (r.next()) {
                txtNombre.setText(r.getString("nombre"));
                txtApellido.setText(r.getString("apellidos"));
                txtDNI.setText(r.getString("dni"));
                txtDireccion.setText(r.getString("direccion"));
                txtTelefono.setText(r.getString("telefono"));
                txtCorreo.setText(r.getString("correo"));
                txtEdad.setText(String.valueOf(r.getInt("edad")));
                txtProvincia.setText(r.getString("provincia"));
                txtPoblacion.setText(r.getString("poblacion"));
                actdesControles(true);//Habilitamos la escritura en el formulario
            } else {
                Mensaje CuadroMensaje = new Mensaje("DNI no encontrado");
                CuadroMensaje.setModal(true);
                CuadroMensaje.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btbCerrarActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        int result;//Registros afectados
        Mensaje CuadroMensaje;
        //Almacenamos los valores en un array 
        String[] datos = new String[10];
        datos[0] = txtDNI.getText();
        datos[1] = txtNombre.getText();
        datos[2] = txtApellido.getText();
        datos[3] = txtEdad.getText();
        datos[4] = txtDireccion.getText();
        datos[5] = txtPoblacion.getText();
        datos[6] = txtProvincia.getText();
        datos[7] = txtTelefono.getText();
        datos[8] = txtCorreo.getText();
        datos[9] = txtValor.getText();
        //Pasamos los valores a la función para modificarlos
        result = miagenda.modificaContacto(datos);
        //En caso de registro afectado
        if (result > 0) {
            txtNombre.setText("");
            txtApellido.setText("");
            txtDNI.setText("");
            txtPoblacion.setText("");
            txtProvincia.setText("");
            txtEdad.setText("");
            txtCorreo.setText("");
            txtTelefono.setText("");
            txtDireccion.setText("");
            actdesControles(false);//Deshabilitamos la escritura en los textfield
            CuadroMensaje = new Mensaje("Cambios aplicados");
        } 
        //Si ningún registro fue afectado
        else {
            CuadroMensaje = new Mensaje("Errores en los datos a modificar"
                    + miagenda.obtenerMensajeError());
        }
        CuadroMensaje.setModal(true);
        CuadroMensaje.setVisible(true);

    }//GEN-LAST:event_btnAplicarActionPerformed
    //Función para permitir o no editar el formulario
    private void actdesControles(boolean val) {
        txtNombre.setEditable(val);
        txtApellido.setEditable(val);
        txtDNI.setEditable(val);
        txtDireccion.setEditable(val);
        txtTelefono.setEditable(val);
        txtCorreo.setEditable(val);
        txtEdad.setEditable(val);
        txtProvincia.setEditable(val);
        txtPoblacion.setEditable(val);
        btnAplicar.setEnabled(val);
        txtValor.setEditable(!val);//Se activa de forma inversa al resto de controles
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCerrar;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnModifica;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
