/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basesDeDatos;

/**
 *
 * @author JazBass
 */
public class formbajas extends javax.swing.JFrame {

    public controlbd miagenda;
    public formbajas() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCampo = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        btnBaja = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Elija campo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Escriba valor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        txtCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dni", "apellidos", "telefono", "correo" }));
        getContentPane().add(txtCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, -1));

        btnBaja.setText("Realizar Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int r;
        Mensaje CuadroMensaje;
        //Seleccionamos la columna para la condición delete ademas del valor de la misma 
        r = miagenda.bajaContacto((String) txtCampo.getSelectedItem(), txtValor.getText());
        //Si uno o más registros fueron afectados
        if (r>0) {
            CuadroMensaje=new Mensaje("Baja realizada");
            txtValor.setText("");
            txtCampo.setSelectedIndex(0);
        }
        //Si ningún registro fue dado de baja, damos aviso
        else{
            CuadroMensaje=new Mensaje("Error en la baja: "+
                    miagenda.obtenerMensajeError());
        }
        CuadroMensaje.setModal(true);
        CuadroMensaje.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> txtCampo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
